version: '3.8'

services:
  db:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - '5439:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/
  pg_admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'

volumes:
    pg_data: