version: '3.8'

services:
  nifi_app:
    container_name: nifi_app_container
    image: apache/nifi
    environment:
      NIFI_WEB_HTTPS_PORT: '9300'
      SINGLE_USER_CREDENTIALS_USERNAME: 'admin'
      SINGLE_USER_CREDENTIALS_PASSWORD: 'pwpw12345678'
    ports:
      - '9300:9300'
    volumes:
      - nifi_app_volume:/opt/nifi/nifi-current/ls-target

volumes:
    nifi_app_volume: